-- Additive migration: run against the existing database before deploying core/board.
-- Nullable fields preserve old accounts, unknown emails and join dates.
BEGIN;
ALTER TABLE users ADD COLUMN IF NOT EXISTS nickname VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(254);
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_status VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS suspended_until TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_version BIGINT;
CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON users(email);
CREATE TABLE IF NOT EXISTS admin_member_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT,
  user_id BIGINT,
  action VARCHAR(255),
  created_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS admin_member_actions_user_id_idx ON admin_member_actions(user_id, id DESC);
COMMIT;
