-- REV.CC 기준(baseline) 스키마. Flyway 도입 직전 운영 DB(Neon)의 스키마를 그대로 옮긴 것이다.
-- 이전에는 Hibernate ddl-auto:update, backend/migrations/*.sql(수동), board-service schema.sql(매 부팅),
-- VehicleRepository(@PostConstruct)가 각자 테이블을 만들었다. 이제 스키마는 Flyway만 변경한다.
--
-- 이미 테이블이 있는 DB는 baseline-on-migrate로 이 파일을 실행하지 않고 "적용됨"으로만 기록한다.
-- 따라서 이 파일은 수정하지 않는다. 스키마 변경은 항상 새 버전(V2, V3, ...) 파일로 추가한다.

-- 회원. 인증과 로그인 이름은 여기에만 둔다(unique 제약 이름은 Hibernate가 생성했던 이름 그대로).
CREATE TABLE users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 password VARCHAR(255) NOT NULL,
 username VARCHAR(255) NOT NULL CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE,
 kakao_id BIGINT CONSTRAINT ukk4ycaj27putgcujmehwbsrmmc UNIQUE,
 role VARCHAR(255) NOT NULL DEFAULT 'USER',
 -- 이전 회원의 알 수 없는 가입일은 NULL로 둔다. 신규 가입일은 Spring User가 기록한다.
 created_at TIMESTAMP(6) WITH TIME ZONE,
 account_status VARCHAR(255),
 auth_version BIGINT,
 email VARCHAR(254) CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE,
 nickname VARCHAR(255),
 suspended_until TIMESTAMP(6) WITH TIME ZONE
);
-- 과거 수동 마이그레이션(20260929_member_management.sql)이 만든 인덱스. 위 unique 제약과 중복이지만 운영 DB에 있으므로 유지한다.
CREATE UNIQUE INDEX users_email_unique ON users(email);

CREATE TABLE admin_member_actions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 action VARCHAR(255),
 admin_id BIGINT,
 created_at TIMESTAMP(6) WITH TIME ZONE,
 user_id BIGINT
);
CREATE INDEX admin_member_actions_user_id_idx ON admin_member_actions(user_id, id DESC);

-- 공용 차량 카탈로그(GET /api/vehicles). 소유 차량(owner_vehicles)과는 별개다.
CREATE TABLE vehicles (
 id BIGINT PRIMARY KEY,
 brand VARCHAR(100) NOT NULL,
 model VARCHAR(100) NOT NULL,
 year INTEGER NOT NULL,
 power INTEGER NOT NULL
);
INSERT INTO vehicles(id, brand, model, year, power)
VALUES (1, 'Hyundai', 'Avante N', 2024, 280), (2, 'BMW', '320i', 2018, 184);

CREATE TABLE community_images (
 id SERIAL PRIMARY KEY,
 owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 mime VARCHAR(30) NOT NULL,
 data BYTEA NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 소유 차량(Spring Vehicle 엔티티, board 차고 화면이 함께 사용).
-- verification_status는 인증 신청 전이면 NULL이다.
CREATE TABLE owner_vehicles (
 id SERIAL PRIMARY KEY,
 owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 model VARCHAR(100) NOT NULL,
 year INTEGER NOT NULL CHECK(year BETWEEN 1900 AND 2100),
 trim VARCHAR(100) NOT NULL DEFAULT '',
 bio VARCHAR(1000) NOT NULL DEFAULT '',
 image_id INTEGER REFERENCES community_images(id),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 color VARCHAR(100) NOT NULL DEFAULT '',
 manufacturer VARCHAR(100) NOT NULL DEFAULT '',
 nickname VARCHAR(100) NOT NULL DEFAULT '',
 transmission VARCHAR(50) NOT NULL DEFAULT '',
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 license_plate VARCHAR(20) NOT NULL DEFAULT '',
 verified BOOLEAN NOT NULL DEFAULT false,
 verification_status VARCHAR(255),
 verified_at TIMESTAMPTZ
);
CREATE INDEX owner_vehicles_owner ON owner_vehicles(owner_id, id);

-- 자동차등록증 원본. community_images(공개 게시글 사진)와 완전히 분리된 테이블로,
-- 소유자 본인과 관리자만 조회할 수 있도록 Spring 쪽에서 접근을 제한한다.
CREATE TABLE vehicle_verifications (
 id SERIAL PRIMARY KEY,
 vehicle_id INTEGER NOT NULL REFERENCES owner_vehicles(id) ON DELETE CASCADE,
 status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
 document_mime VARCHAR(30) NOT NULL,
 document_data BYTEA NOT NULL,
 requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 reviewed_at TIMESTAMPTZ,
 reviewed_by BIGINT REFERENCES users(id)
);
CREATE INDEX vehicle_verifications_vehicle ON vehicle_verifications(vehicle_id, id DESC);
CREATE INDEX vehicle_verifications_status ON vehicle_verifications(status, id DESC);

CREATE TABLE vehicle_records (
 id SERIAL PRIMARY KEY,
 vehicle_id INTEGER NOT NULL REFERENCES owner_vehicles(id) ON DELETE CASCADE,
 kind VARCHAR(20) NOT NULL,
 title VARCHAR(150) NOT NULL,
 content VARCHAR(2000) NOT NULL DEFAULT '',
 mileage INTEGER CHECK(mileage BETWEEN 0 AND 2000000),
 cost INTEGER CHECK(cost BETWEEN 0 AND 2000000000),
 recorded_on DATE NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 커뮤니티(board-service).
CREATE TABLE board_posts (
 id SERIAL PRIMARY KEY,
 title VARCHAR(150) NOT NULL,
 content TEXT NOT NULL,
 author_id BIGINT NOT NULL REFERENCES users(id),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 category VARCHAR(20) NOT NULL DEFAULT 'free',
 vehicle VARCHAR(100) NOT NULL DEFAULT '',
 image_ids INTEGER[] NOT NULL DEFAULT '{}',
 views INTEGER NOT NULL DEFAULT 0,
 updated_at TIMESTAMPTZ,
 vehicle_id INTEGER REFERENCES owner_vehicles(id) ON DELETE SET NULL,
 deleted BOOLEAN NOT NULL DEFAULT false
);
CREATE INDEX board_posts_category_id ON board_posts(category, id DESC);
CREATE INDEX board_posts_author_id ON board_posts(author_id, id DESC);

CREATE TABLE board_comments (
 id SERIAL PRIMARY KEY,
 post_id INTEGER NOT NULL REFERENCES board_posts(id) ON DELETE CASCADE,
 author_id BIGINT NOT NULL REFERENCES users(id),
 parent_id INTEGER REFERENCES board_comments(id) ON DELETE CASCADE,
 content VARCHAR(2000) NOT NULL,
 deleted BOOLEAN NOT NULL DEFAULT false,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX board_comments_post ON board_comments(post_id, id);

CREATE TABLE board_likes (
 post_id INTEGER NOT NULL REFERENCES board_posts(id) ON DELETE CASCADE,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 PRIMARY KEY(post_id, user_id)
);

CREATE TABLE board_bookmarks (
 post_id INTEGER NOT NULL REFERENCES board_posts(id) ON DELETE CASCADE,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 PRIMARY KEY(post_id, user_id)
);

CREATE TABLE community_notifications (
 id SERIAL PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 actor_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 post_id INTEGER NOT NULL REFERENCES board_posts(id) ON DELETE CASCADE,
 kind VARCHAR(20) NOT NULL,
 is_read BOOLEAN NOT NULL DEFAULT false,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX community_notifications_user ON community_notifications(user_id, id DESC);

CREATE TABLE community_reports (
 id SERIAL PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 post_id INTEGER NOT NULL REFERENCES board_posts(id) ON DELETE CASCADE,
 reason VARCHAR(500) NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'pending',
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 reviewed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
 reviewed_at TIMESTAMPTZ,
 resolution_note VARCHAR(500) NOT NULL DEFAULT '',
 UNIQUE(user_id, post_id)
);
CREATE INDEX community_reports_status_id ON community_reports(status, id DESC);

-- 선택 입력 개인 설정. 인증과 로그인 이름은 users에 남는다.
CREATE TABLE member_profiles (
 user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
 bio VARCHAR(300) NOT NULL DEFAULT '',
 avatar_image_id INTEGER REFERENCES community_images(id) ON DELETE SET NULL,
 cover_image_id INTEGER REFERENCES community_images(id) ON DELETE SET NULL,
 representative_vehicle_id INTEGER REFERENCES owner_vehicles(id) ON DELETE SET NULL
);

CREATE TABLE garage_guestbook (
 id SERIAL PRIMARY KEY,
 owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 content VARCHAR(1000) NOT NULL CHECK(length(btrim(content)) > 0),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX garage_guestbook_owner ON garage_guestbook(owner_id, id DESC);

-- 부품 장터 매물은 커뮤니티 게시글이 아니다. 회원과 공개 이미지 업로드만 재사용한다.
CREATE TABLE parts_listings (
 id SERIAL PRIMARY KEY,
 seller_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 title VARCHAR(150) NOT NULL,
 description VARCHAR(5000) NOT NULL,
 price BIGINT NOT NULL CHECK(price BETWEEN 0 AND 2000000000),
 category VARCHAR(30) NOT NULL CHECK(category IN ('wheels','suspension','brakes','intake-exhaust','exterior','interior','electronics','engine','other')),
 status VARCHAR(15) NOT NULL DEFAULT 'selling' CHECK(status IN ('selling','reserved','sold')),
 image_ids INTEGER[] NOT NULL DEFAULT '{}',
 vehicle VARCHAR(200) NOT NULL,
 region VARCHAR(100) NOT NULL,
 contact VARCHAR(300) NOT NULL,
 views INTEGER NOT NULL DEFAULT 0,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ
);
CREATE INDEX parts_listings_seller ON parts_listings(seller_id, id DESC);
CREATE INDEX parts_listings_category_status ON parts_listings(category, status, id DESC);

CREATE TABLE parts_favorites (
 listing_id INTEGER NOT NULL REFERENCES parts_listings(id) ON DELETE CASCADE,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 PRIMARY KEY(listing_id, user_id)
);
CREATE INDEX parts_favorites_user ON parts_favorites(user_id, listing_id);

-- 관리자 삭제 기록. 로그는 게시글/댓글을 참조하지 않는 변경 불가 스냅샷이다.
CREATE TABLE moderation_logs (
 id BIGSERIAL PRIMARY KEY,
 action_type VARCHAR(20) NOT NULL CHECK(action_type IN ('POST_DELETE','COMMENT_DELETE','REPLY_DELETE')),
 category VARCHAR(20) NOT NULL,
 post_id INTEGER NOT NULL,
 post_title VARCHAR(150) NOT NULL,
 target_id INTEGER NOT NULL,
 target_author_id BIGINT NOT NULL,
 target_author_username TEXT NOT NULL,
 original_content TEXT NOT NULL,
 reason VARCHAR(500) NOT NULL CHECK(length(btrim(reason)) > 0),
 admin_id BIGINT NOT NULL,
 admin_username TEXT NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
